### ISSUE TITLE
mouse assembly

### ISSUE THREAD

**Issue by santiago-es** [bioinfo-chru-strasbourg/vcf2circos#25]
Hi,

Thank you for making this tool available to the community. 

I have a VCF and an assembled genome for mouse long-read sequencing data. I would like to make a circos plot to visualize this. It looks like there are no mouse genome assemblies in the current build. Would you be able to provide one or provide instructions on how to appropriately add one to the Assemblies to make this possible?

Thank you

**Comment by JbaptisteLam** [comment]
Hi,
Indeed we don't have set up the mouse assembly in the configuration folder for now but it will be soon available,
I think it will require some adaptations too,

Best,

Jean-Baptiste

**Comment by tuannguyen8390** [comment]
Hi there,

Keen to follow up on this, it would be nice if we have some sort of tutorial on how to prepare the assembly. 

In my case it is cattle.

Best,

Tuan

**Comment by JbaptisteLam** [comment]
Hi, comming to you very late sorry for that,
Effectively I just release a new version (more a patch than a release) handling mouse assembly, and I'm actually updating the README.md with the preparation of genome assembly, it will be there later in the day,

Best,

Jean-Baptiste

**Comment by MitoSri** [comment]
Hi Jean! Just following up to see if the preparation of genome assembly for mouse is updated. I am trying to create one for mm10. I end up with an error 
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/raulab/Desktop/vcf2circos/vcf2circos/utils.py", line 309, in formatted_refgene
    with gzip.open(output_exons, "wb+") as out_e:
  File "/home/raulab/anaconda3/lib/python3.9/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/home/raulab/anaconda3/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '~/Desktop/vcf2circos/config_vcf2circos_09012023/Assembly/mm39/exons.mm39.txt.gz'`

**Comment by JbaptisteLam** [comment]
Hi,

Sorry about that,
Can you provide me your ncbi file I will try to figure out what's going on,
You can send files to this mail jean-baptiste.lamouche@chru-strasbourg.fr

Best,

Jean-Baptiste

**Comment by MitoSri** [comment]
Hello Jean. Sorry I wasn't following up with the issue for a long time. I downloaded the latest config files and its working. This time its a different issue
I need a solution to display variants in the mitochondrial contigs. My variant calling is mostly in the mitochondrial DNA and when I use the unfiltered VCF with all contigs, I get the output without the chrM region. When I filter the chrM contigs and run, I get the error "No variants in /home/lab/Desktop/vcf2circos/config_vcf2circos/Static/output.vcf EXIT"
I tried including "chrM" in json file chromosome list:"chrM"..still not working. 
Is there any other solution ? as I noticed that the assembly for mm10 has MT genes in all files except the cytoband info
