### ISSUE TITLE
failed with vcf output from AnnotSV

### ISSUE THREAD

**Issue by lmanchon** [bioinfo-chru-strasbourg/vcf2circos#31]
vcf2circos --input mylib_annotated.vcf --options Static/options.json --output mylib.html -a hg38

-._    _.--'"`'--._    _.--'"`'--._    _.--'"`'--._    _
    '-:`.'|`|"':-.  '-:`.'|`|"':-.  '-:`.'|`|"':-.  '.` : '.
  '.  '.  | |  | |'.  '.  | |  | |'.  '.  | |  | |'.  '.:   '.  '.
  : '.  '.| |  | |  '.  '.| |  | |  '.  '.| |  | |  '.  '.  : '.  `.
  '   '.  `.:_ | :_.' '.  `.:_ | :_.' '.  `.:_ | :_.' '.  `.'   `.
         `-..,..-'       `-..,..-'       `-..,..-'       `         `

                     __ ___      _
                    / _|__ \    (_)
         __   _____| |_   ) |___ _ _ __ ___ ___  ___
         \ \ / / __|  _| / // __| | '__/ __/ _ \/ __|
          \ V / (__| |  / /| (__| | | | (_| (_) \__ \
           \_/ \___|_| |____\___|_|_|  \___\___/|___/

Author: Jean-Baptiste Lamouche, Antony Le Bechec, Jin Cui
Version: 1.1
Last update: Mars 26 2023

[INFO] Input file: mylib_annotated.vcf (format 'vcf')
[INFO] Output file: mylib.html (format 'html')
[INFO] Options provided.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/vcf/parser.py", line 518, in _parse_info
    val = self._map(int, vals)
  File "/usr/local/lib/python3.8/dist-packages/vcf/parser.py", line 475, in _map
    return [func(x) if x not in bad else None for x in iterable]
  File "/usr/local/lib/python3.8/dist-packages/vcf/parser.py", line 475, in <listcomp>
    return [func(x) if x not in bad else None for x in iterable]
ValueError: invalid literal for int() with base 10: '24.0|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/NGS/.local/bin/vcf2circos", line 33, in <module>
    sys.exit(load_entry_point('vcf2circos', 'console_scripts', 'vcf2circos')())
  File "/home/NGS/vcf2circos/vcf2circos/__main__.py", line 119, in main
    js = Datafactory(input_file, options).plot_dict()
  File "/home/NGS/vcf2circos/vcf2circos/datafactory.py", line 25, in plot_dict
    pc = Plotconfig(
  File "/home/NGS/vcf2circos/vcf2circos/plotcategories/plotconfig.py", line 100, in __init__
    self.data = self.process_vcf()
  File "/home/NGS/vcf2circos/vcf2circos/utils.py", line 481, in timeit_wrapper
    result = func(*args, **kwargs)
  File "/home/NGS/vcf2circos/vcf2circos/plotcategories/plotconfig.py", line 150, in process_vcf
    for record in self.vcf_reader:
  File "/usr/local/lib/python3.8/dist-packages/vcf/parser.py", line 706, in __next__
    info = self._parse_info(row[7])
  File "/usr/local/lib/python3.8/dist-packages/vcf/parser.py", line 522, in _parse_info
    val = self._map(float, vals)
  File "/usr/local/lib/python3.8/dist-packages/vcf/parser.py", line 475, in _map
    return [func(x) if x not in bad else None for x in iterable]
  File "/usr/local/lib/python3.8/dist-packages/vcf/parser.py", line 475, in <listcomp>
    return [func(x) if x not in bad else None for x in iterable]
ValueError: could not convert string to float: '24.0|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.'

**Comment by JbaptisteLam** [comment]
Hi, 
I think it's due to the metaheader specs, can you send me a part of your vcf, or just the header and a few variants, it will be easier to consider,

Best,

Jean-Baptiste

**Comment by lmanchon** [comment]
--Hi,
see here in attachment my complete vcf generated by AnnotSV.
thank you
[my_AnnotSV.vcf.zip](https://github.com/bioinfo-chru-strasbourg/vcf2circos/files/12311203/my_AnnotSV.vcf.zip)
