### ISSUE TITLE
Can not find Assembly

### ISSUE THREAD

**Issue by qingxiangguo** [bioinfo-chru-strasbourg/vcf2circos#34]
vcf2circos -i ../pbsv/PC3_10cell.var.vcf -o PC3_100cell.html -a /home/qgn1237/2_software/config_vcf2circos_21082023/Static/Assembly/hg38 -p /home/qgn1237/2_software/config_vcf2circos_21082023/Static/options.json

vcf2circos -i ../pbsv/PC3_10cell.var.vcf -o PC3_100cell.html -a hg38 -p /home/qgn1237/2_software/config_vcf2circos_21082023/Static/options.json

Hi

I've tried both command and I get

[INFO] Input file: ../pbsv/PC3_10cell.var.vcf (format 'vcf')
[INFO] Output file: PC3_100cell.html (format 'html')
[INFO] Options provided.
Traceback (most recent call last):
  File "/home/qgn1237/2_software/mambaforge/envs/vcf2circos/bin/vcf2circos", line 8, in <module>
    sys.exit(main())
  File "/home/qgn1237/2_software/vcf2circos/vcf2circos/__main__.py", line 95, in main
    assert args.assembly in os.listdir(osj(options["Static"], "Assembly")), (
FileNotFoundError: [Errno 2] No such file or directory: 'Assembly'

Would you mind give some ideas about how to use the Assemby?

**Comment by JbaptisteLam** [comment]
Hi,
You have to set the path of folder containing Assembly folder in the options.json in the key "Static", so in your case it will be "Static": "/home/qgn1237/2_software/config_vcf2circos_21082023/Static",

Best,

JB
