### ISSUE TITLE
KeyError: 'Variants'

### ISSUE THREAD

**Issue by makise58** [bioinfo-chru-strasbourg/vcf2circos#35]
Hi.
I'm trying to visualize structural variants using vcf2circos.

I annotated the vcf file using AnnotSV.
```
$ AnnotSV \
	-SVinputFile sample.vcf \
	-outputDir sample \
	-vcf 1 \
	-svtBEDcol 4
```

Then I tried vcf2circos but it failed.
I also tried example.vcf, test_copy_numbet.vcf, test_empty.vcf, test_gene_matcher.vcf, and test_transloc.vcf, all of which gave the same error.
How can I fix it??
Thanks.

```
$ vcf2circos \
	-i sample.annotated.vcf \
	-o sample_vcf2circos.pdf \
	-a hg38
```
```
-._    _.--'"`'--._    _.--'"`'--._    _.--'"`'--._    _
    '-:`.'|`|"':-.  '-:`.'|`|"':-.  '-:`.'|`|"':-.  '.` : '.
  '.  '.  | |  | |'.  '.  | |  | |'.  '.  | |  | |'.  '.:   '.  '.
  : '.  '.| |  | |  '.  '.| |  | |  '.  '.| |  | |  '.  '.  : '.  `.
  '   '.  `.:_ | :_.' '.  `.:_ | :_.' '.  `.:_ | :_.' '.  `.'   `.
         `-..,..-'       `-..,..-'       `-..,..-'       `         `

                     __ ___      _
                    / _|__ \    (_)
         __   _____| |_   ) |___ _ _ __ ___ ___  ___
         \ \ / / __|  _| / // __| | '__/ __/ _ \/ __|
          \ V / (__| |  / /| (__| | | | (_| (_) \__ \
           \_/ \___|_| |____\___|_|_|  \___\___/|___/



Author: Jean-Baptiste Lamouche, Antony Le Bechec, Jin Cui
Version: 1.1.1
Last update: 16 August 2023


[INFO] Input file: sample.annotated.vcf (format 'vcf')
[INFO] Output file: sample.pdf (format 'pdf')
[INFO] Options not provided.


Traceback (most recent call last):
  File "/home/makise/anaconda3/bin/vcf2circos", line 8, in <module>
    sys.exit(main())
  File "/home/makise/vcf2circos/vcf2circos/__main__.py", line 119, in main
    js = Datafactory(input_file, options).plot_dict()
  File "/home/makise/vcf2circos/vcf2circos/datafactory.py", line 17, in __init__
    val = options["Variants"]["rings"]["position"] + options["Variants"]["rings"]["space"]
KeyError: 'Variants'


```

**Comment by JbaptisteLam** [comment]
Hi,

You have to provide the configuration file in options with "-p" arg, 
Default configuration file is provided in the configuration folder here http://www.lbgi.fr/~lamouche/vcf2circos/ 

Best,

JB

**Comment by makise58** [comment]
@JbaptisteLam 

Thanks for your reply.
I downloaded configuration folders.

I tried "-p" arg, but another error occurred even though "Assembly" directory exists.

```
vcf2circos \
--input sample.annotated.vcf \
--output sample,annotated.html \
-p ~/vcf2circos/config_vcf2circos_21082023/Static/options.json \
-a hg38
```
```
-._    _.--'"`'--._    _.--'"`'--._    _.--'"`'--._    _
    '-:`.'|`|"':-.  '-:`.'|`|"':-.  '-:`.'|`|"':-.  '.` : '.
  '.  '.  | |  | |'.  '.  | |  | |'.  '.  | |  | |'.  '.:   '.  '.
  : '.  '.| |  | |  '.  '.| |  | |  '.  '.| |  | |  '.  '.  : '.  `.
  '   '.  `.:_ | :_.' '.  `.:_ | :_.' '.  `.:_ | :_.' '.  `.'   `.
         `-..,..-'       `-..,..-'       `-..,..-'       `         `

                     __ ___      _
                    / _|__ \    (_)
         __   _____| |_   ) |___ _ _ __ ___ ___  ___
         \ \ / / __|  _| / // __| | '__/ __/ _ \/ __|
          \ V / (__| |  / /| (__| | | | (_| (_) \__ \
           \_/ \___|_| |____\___|_|_|  \___\___/|___/



Author: Jean-Baptiste Lamouche, Antony Le Bechec, Jin Cui
Version: 1.1.1
Last update: 16 August 2023


[INFO] Input file: sample.annotated.vcf (format 'vcf')
[INFO] Output file: sample,annotated.html (format 'html')
[INFO] Options provided.
Traceback (most recent call last):
  File "/home/makise/anaconda3/bin/vcf2circos", line 8, in <module>
    sys.exit(main())
  File "/home/makise/vcf2circos/vcf2circos/__main__.py", line 95, in main
    assert args.assembly in os.listdir(osj(options["Static"], "Assembly")), (
FileNotFoundError: [Errno 2] No such file or directory: 'Assembly'
```

I also tried pre-existed json file, but another error occured.
Can I fix these errors??
Thanks.

```
vcf2circos \
--input sample.annotated.vcf \
--output sample,annotated.html \
-p ~/vcf2circos/Static/options.json \
-a hg38
```
```
-._    _.--'"`'--._    _.--'"`'--._    _.--'"`'--._    _
    '-:`.'|`|"':-.  '-:`.'|`|"':-.  '-:`.'|`|"':-.  '.` : '.
  '.  '.  | |  | |'.  '.  | |  | |'.  '.  | |  | |'.  '.:   '.  '.
  : '.  '.| |  | |  '.  '.| |  | |  '.  '.| |  | |  '.  '.  : '.  `.
  '   '.  `.:_ | :_.' '.  `.:_ | :_.' '.  `.:_ | :_.' '.  `.'   `.
         `-..,..-'       `-..,..-'       `-..,..-'       `         `

                     __ ___      _
                    / _|__ \    (_)
         __   _____| |_   ) |___ _ _ __ ___ ___  ___
         \ \ / / __|  _| / // __| | '__/ __/ _ \/ __|
          \ V / (__| |  / /| (__| | | | (_| (_) \__ \
           \_/ \___|_| |____\___|_|_|  \___\___/|___/



Author: Jean-Baptiste Lamouche, Antony Le Bechec, Jin Cui
Version: 1.1.1
Last update: 16 August 2023


[INFO] Input file: sample.annotated.vcf (format 'vcf')
[INFO] Output file: sample.annotated.html (format 'html')
[INFO] Options provided.
Traceback (most recent call last):
  File "/home/makise/anaconda3/bin/vcf2circos", line 8, in <module>
    sys.exit(main())
  File "/home/makise/vcf2circos/vcf2circos/__main__.py", line 95, in main
    assert args.assembly in os.listdir(osj(options["Static"], "Assembly")), (
FileNotFoundError: [Errno 2] No such file or directory: '/enadisk/maison/lamouche/dev_vcf2circos/Static/Assembly'
```

**Comment by JbaptisteLam** [comment]
Hi, 

You need to fill the "Static" key in the json file with the absolute path of your Static folder provided in the configuration folder regarding where you placed it,
"Static": ""  -> "Static": "Path of static folder"

Best,

Jean-Baptiste

**Comment by makise58** [comment]
@JbaptisteLam 
Thanks!
It worked!
