### ISSUE TITLE
cannot import name 'Reader' from 'parser'

### ISSUE THREAD

**Issue by jingydz** [bioinfo-chru-strasbourg/vcf2circos#37]
Hi, I installed the vcf2circos.
git clone https://github.com/bioinfo-chru-strasbourg/vcf2circos.git
cd vcf2circos
python -m pip install -e .

I test the command "vcf2circos", and get the output on the terminal.
$ vcf2circos

-._    _.--'"`'--._    _.--'"`'--._    _.--'"`'--._    _
    '-:`.'|`|"':-.  '-:`.'|`|"':-.  '-:`.'|`|"':-.  '.` : '.
  '.  '.  | |  | |'.  '.  | |  | |'.  '.  | |  | |'.  '.:   '.  '.
  : '.  '.| |  | |  '.  '.| |  | |  '.  '.| |  | |  '.  '.  : '.  `.
  '   '.  `.:_ | :_.' '.  `.:_ | :_.' '.  `.:_ | :_.' '.  `.'   `.
         `-..,..-'       `-..,..-'       `-..,..-'       `         `

                     __ ___      _
                    / _|__ \    (_)
         __   _____| |_   ) |___ _ _ __ ___ ___  ___
         \ \ / / __|  _| / // __| | '__/ __/ _ \/ __|
          \ V / (__| |  / /| (__| | | | (_| (_) \__ \
           \_/ \___|_| |____\___|_|_|  \___\___/|___/

Author: Jean-Baptiste Lamouche, Antony Le Bechec, Jin Cui
Version: 1.1.1
Last update: 16 August 2023

Traceback (most recent call last):
  File "/xxx/software/miniconda3/bin/vcf2circos", line 5, in <module>
    from vcf2circos.__main__ import main
  File "/xxx/software/vcf2circos/vcf2circos/__main__.py", line 5, in <module>
    from vcf2circos.datafactory import Datafactory
  File "/xxx/software/vcf2circos/vcf2circos/datafactory.py", line 1, in <module>
    from vcf2circos.plotcategories.histogram import Histogram_
  File "/xxx/software/vcf2circos/vcf2circos/plotcategories/histogram.py", line 3, in <module>
    from vcf2circos.plotcategories.plotconfig import Plotconfig
  File "/xxx/software/vcf2circos/vcf2circos/plotcategories/plotconfig.py", line 19, in <module>
    import vcf
  File "/xxx/.local/lib/python3.9/site-packages/vcf/__init__.py", line 166, in <module>
    from parser import Reader, Writer
ImportError: cannot import name 'Reader' from 'parser' (/xxx/software/miniconda3/lib/python3.9/lib-dynload/parser.cpython-39-x86_64-linux-gnu.so)

**Comment by JbaptisteLam** [comment]
Hi,

I had similar trouble before when I created a homemade python package called vcf too. It could be the problem. Check your libraries with "python -m pip list "to see if you have packages named "vcf". If so, uninstall them and try again.

Best,

JB
