### ISSUE TITLE
Support for human T2T assembly

### ISSUE THREAD

**Issue by bwlang** [bioinfo-chru-strasbourg/vcf2circos#39]
I was not able to find  the expected input files for construction of the assembly.

(https://hgdownload.soe.ucsc.edu/gbdb/hs1/ does not seem to have ncbiRefSeqCurated.txt.gz, chromInfo.txt.gz, cytoBand.txt.gz).

is there an alternative using the bigbed files that they do have?
e.g.
https://hgdownload.soe.ucsc.edu/gbdb/hs1/bbi/ncbiRefSeqCurated.bb
https://hgdownload.soe.ucsc.edu/gbdb/hs1/hubs/chromAlias.txt
https://hgdownload.soe.ucsc.edu/gbdb/hs1/cytoBandMapped/cytoBandMapped.bb

Thanks for any advice...

**Comment by thomasguignard** [comment]
Hello,
You can first transform bigbed files to bed with this ucsc application:
https://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigBedToBed
e.g.
bigBedToBed  ncbiRefSeqCurated.bb  ncbiRefSeqCurated.bed

Then sort as recommended: 
sort -k1,1V -k2,2n  ncbiRefSeqCurated.bed > ncbiRefSeqCurated_sort.bed

**Comment by gbdias** [comment]
It looks like the [ncbiRefSeqCurated files](https://hgdownload.soe.ucsc.edu/gbdb/hs1/) for the T2T assembly do not follow the same schema as for hg19 and hg38. This causes vcf2circos to complain with this error:

`python -c "from utils import formatted_refgene; formatted_refgene('/Users/guibo205/Documents/GitHub/vcf2circos/config_vcf2circos_21082023/Static/Assembly/t2t/ncbiRefSeqCurated_sorted.bed', 't2t')"`
```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/guibo205/Documents/GitHub/vcf2circos/vcf2circos/utils.py", line 297, in formatted_refgene
    assert (
AssertionError: Error in columns format more or less than 16 columns, expected
	cols: bin,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,score,name2,cdsStartStat,cdsEndStat,exonFrames
```
