### ISSUE TITLE
Error : cannot import name 'CSS3_HEX_TO_NAMES' from 'webcolors'

### ISSUE THREAD

**Issue by tomgutman** [bioinfo-chru-strasbourg/vcf2circos#44]
Hi,

I installed vcf2circos via mamba `mamba create --name vcf2circos -c bioconda vcf2circos`

After loading the environement I got the following error : 

```
vcf2circos -h
Traceback (most recent call last):
  File "/mnt/beegfs/userdata/t_gutman/miniforge3/envs/vcf2circos/bin/vcf2circos", line 6, in <module>
    from vcf2circos.__main__ import main
  File "/mnt/beegfs/userdata/t_gutman/miniforge3/envs/vcf2circos/lib/python3.12/site-packages/vcf2circos/__main__.py", line 27, in <module>
    from fig import Figure
  File "/mnt/beegfs/userdata/t_gutman/miniforge3/envs/vcf2circos/lib/python3.12/site-packages/vcf2circos/./fig.py", line 21, in <module>
    from webcolors import CSS3_HEX_TO_NAMES, hex_to_rgb
ImportError: cannot import name 'CSS3_HEX_TO_NAMES' from 'webcolors' (/mnt/beegfs/userdata/t_gutman/miniforge3/envs/vcf2circos/lib/python3.12/site-packages/webcolors/__init__.py)
```

Would you have a fix or a workaround using mamba ? 

Thanks
Tom

**Comment by JbaptisteLam** [comment]
Hi,

It's due to the version of webcolors library, the conda recipe is not up to date with the latest release,
Try to install it in your mamba env with pip from the setup.cfg recipe,
mamba create -n vcf2circos python==3.10.13
mamba activate vcf2circos
go inside the repository and pip install -e .

Best,

Jean-Baptiste

**Comment by Hugbenny** [comment]
Hey,

The problem is also present using docker, and updating the Dockerfile by puting python 3.11.9 instead of python 3.9 doesn't seems to work (but python 3.11.9 is used by conda)
```
File "/usr/local/lib/python3.11/site-packages/vcf2circos/__main__.py", line 27, in <module>
    from fig import Figure
  File "/usr/local/lib/python3.11/site-packages/vcf2circos/./fig.py", line 21, in <module>
    from webcolors import CSS3_HEX_TO_NAMES, hex_to_rgb
ImportError: cannot import name 'CSS3_HEX_TO_NAMES' from 'webcolors' (/usr/local/lib/python3.11/site-packages/webcolors/__init__.py)
```

Would you have a workaround ?

Thx,

Ben.
