### ISSUE TITLE
IndexErrors

### ISSUE THREAD

**Issue by albergander** [bioinfo-chru-strasbourg/vcf2circos#46]
Hi, 
I struggle to  understand, why the following error arises. I installed vcf2circos with conda and I rn it with:

vcf2circos -i 22097_DMD.wf_sv.vcf.gz -o 22097_DMD.wf_sv.html -p ../circos/options.json

[INFO] Input file: 22097_DMD.wf_sv.vcf.gz (format 'gz')
[INFO] Output file: 22097_DMD.wf_sv.html (format 'html')
[INFO] Options provided.

Function process_vcf(<vcf2circos.plotcategories.plotconfig.Plotconfig object at 0x7fe8c25fe510>,) {} Took 320.7821 seconds
Function merge_options(<vcf2circos.plotcategories.link.Link object at 0x7fe8b7597230>,) {} Took 3.7747 seconds
[WARN] 5th column is missing for inter-chromosome custom spacing, using default spacing values
[WARN] warning on category "ring"
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/vcf2circos/lib/python3.13/site-packages/vcf2circos/./fig.py", line 1427, in fig
    return go.Figure(data=trace_obj, layout=self.layout())
                                            ~~~~~~~~~~~^^
  File "/home/user/miniconda3/envs/vcf2circos/lib/python3.13/site-packages/vcf2circos/./fig.py", line 1379, in layout
    if isinstance(self.get_paths_dict(key)[0], dict):
                  ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/vcf2circos/bin/vcf2circos", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/user/miniconda3/envs/vcf2circos/lib/python3.13/site-packages/vcf2circos/__main__.py", line 130, in main
    fig = fig_instance.fig()
  File "/home/user/miniconda3/envs/vcf2circos/lib/python3.13/site-packages/vcf2circos/utils.py", line 459, in timeit_wrapper
    result = func(*args, **kwargs)
  File "/home/user/miniconda3/envs/vcf2circos/lib/python3.13/site-packages/vcf2circos/./fig.py", line 1441, in fig
    layout=self.layout(),
           ~~~~~~~~~~~^^
  File "/home/user/miniconda3/envs/vcf2circos/lib/python3.13/site-packages/vcf2circos/./fig.py", line 1379, in layout
    if isinstance(self.get_paths_dict(key)[0], dict):
                  ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range




The option.json contains;

{
        "General": {
                "title": "",
                "width": 1000,
                "height": 1000,
                "plot_bgcolor": "white"
        },
        "Static": "/home/user/circos/Static",
        "Assembly": "hg38",
        "Chromosomes": {
                "list": [],
                "all": false
        },
        "Genes": {
                "only_snv_in_sv_genes": false,
                "extend": false
        },
        "Variants": {
                "annotations": {
                        "fields": []
                },
                "rings": {
                        "position": 0.4,
                        "height": 0.04,
                        "space": 0.01,
                        "nrings": 6
                }
        },
     

Thank you for your help.

**Comment by santiago-es** [comment]
im also getting this issue, using the default options file from the config and assembly hg38
